using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitle("EMMU Generated Application")]
[assembly: AssemblyDescription("Temporary application generated by EMMU RPC")]
[assembly: AssemblyCompany("EMMU")]
[assembly: AssemblyProduct("EMMU Generated Application")]
[assembly: AssemblyCopyright("Copyright © EMMU")]
[assembly: ComVisible(false)]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
